jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest' # other options: 'macOS-latest', 'windows-latest'
  strategy:
    matrix:
      # Python27:
      #   python.version: '2.7'
      Python38:
        python.version: '3.8'
      # Python36:
      #   python.version: '3.6'

  steps:
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '$(python.version)'
  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: |
        print('Hello world 1')
        print('Hello world 2')
  # - task: PythonScript@0
  #   inputs:
  #     scriptSource: inline
  #     script: |
  #       import sys
  #       print ('Executing script file is:', str(sys.argv[0]))
  #       print ('The arguments are:', str(sys.argv))
  #       import argparse
  #       parser = argparse.ArgumentParser()
  #       parser.add_argument("--world", help="Provide the name of the world to greet.")
  #       args = parser.parse_args()
  #       print ('Hello ', args.world)
  #     arguments: --world Venus
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'